""" Migrations
"""

# Generated by Django 4.2.3 on 2023-08-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_oaipmh_harvester_app", "0002_psql_full_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oairecord",
            old_name="xml_file",
            new_name="file",
        ),
    ]
