# Generated by Django 4.2.21 on 2025-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_oaipmh_harvester_app",
            "0003_remove_oairecord_xml_file_oairecord_file",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="oairecord",
            name="file_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
